### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by stawberri** [Nightbug/website#2]
![image](https://cloud.githubusercontent.com/assets/9897819/25801841/627f5be8-33a4-11e7-8e26-4c0b06a5b9cd.png)

---

![image](https://cloud.githubusercontent.com/assets/9897819/25801894/9f0833be-33a4-11e7-89db-3d4a467af610.png)

---

![image](https://cloud.githubusercontent.com/assets/9897819/25801920/c63d4b4a-33a4-11e7-883d-53bbbe15a839.png)

---

![image](https://cloud.githubusercontent.com/assets/9897819/25801936/dbd81ce6-33a4-11e7-8af3-79161eda0e4e.png)

**Comment by coderobe** [comment]
I don't think @pixeldesu can access that domain name anymore

**Comment by nilsding** [comment]
@coderobe that's right

while domain hacks are nice, they are annoying most of the time

**Comment by pixeldesu** [comment]
@coderobe @nilsding @stawberri I can probably still access the domain name, the provider itself has issues tho.

They randomly cancelled my domain, without prior notice, so I have no idea of the actual state of the domain. Maybe switching to something else with a more reliable provider might be an option.

**EDIT:** Looks like the registrar I got the domain from is not even properly existing anymore. Probably the reason my domain just got disabled without reason.

**Comment by stawberri** [comment]
There's always hosting on Github!

**Comment by nilsding** [comment]
this issue has nothing to do with hosting, since the same would have happened if we just used github pages with a CNAME set

anyway, time to grab yet another domain!

**Comment by stawberri** [comment]
Ooooh, I see.
